modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="olympus"
version="1.0.0"
displayName="Olympus"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ManilBe"

[[dependencies.olympus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



